import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../app/styles/index.scss";
import Navbar from "./components/navbar/Navbar";

const roboto = Roboto({
	weight: "400",
	subsets: ["latin"],
});
import { Inter } from "next/font/google";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Navbar />
				{children}
			</body>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
