import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../app/styles/index.scss";
import Navbar from "./components/navbar/Navbar";
import "../app/styles/index.scss";
import Providers from "./Providers";
import { Toaster } from "sonner";

const roboto = Roboto({
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Providers>
					<Toaster richColors position="top-center" />
					<Navbar />
					{children}
				</Providers>
			</body>
		</html>
	);
}
